### PR TITLE
Update format of tax examples to runtime spec 0.4.0

### PR DESCRIPTION
**Pull request by RyanFleck**
Changes:
- Moved old rules to historical-month-year folders.
- Placed package information within rules.
- Added `.table` files to accompany table `.json`.
- Assumed experimental rules would be included in package `org.xalgorithms.examples`.

### CODE REVIEW

**Comment by jpotvin** [comment]
Thanks Ryan!! a few suggestions  and questions. Some of these come from the earlier version you had to start with.

1. In the .package file, you should appear as
 "editor" : {
          "name" : "Ryan Fleck",
"email" : "ryan.fleck@protonmail.com"

2. Is the version 0.0.2 or now 0.0.3 ?

3. I think the URL should be the source of this rule:
"url" : "http://legisquebec.gouv.qc.ca/fr/ShowDoc/cr/T-1,%20r.%201",

4. In the supplier distance table, somewhere in versions the random character IDs were made into ordered numbers. Please replace the 00001 etc with ...
YJ4gh6Ofdq
UsN8EB1QZU
uZz9cKtwhx
HcfUd49gPV
0DXKYXBZr8

5. Line 32, 33, 34 and 37: shouldn't "allowance" be "reduction"?  

That's all for now.

**Comment by RyanFleck** [comment]
In the latest revision, we've done away with the .package file in favor of the inline EFFECTIVE and META data present in the top of .rule files, as seen [here, in a_plus_b.](https://github.com/Xalgorithms/general-examples/tree/master/org.xalgorithms.examples.a_plus_b)

2 => a_plus_b cites 0.4.0 as the revision.

3 => Will add the qc-gas-tax URL.
4 => Will modify the supplier distances with IDs.
5 => Will check and revise if needed.

1 => Will add myself as a maintainer for the sample rules.

**Comment by RyanFleck** [comment]
Closing until revisions are made.

**Comment by jpotvin** [comment]
RE: Line 32, 33, 34 and 37: shouldn't "allowance" be "reduction"

I checked our history of using that word, and it comes from the UBL dictionary.
http://docs.oasis-open.org/ubl/os-UBL-2.1/mod/summary/reports/UBL-AllDocuments-2.1.html#Table_AllowanceCharge.Details

I'm not sure though that this is the best element from UBL to use. I don't currently have a better suggestion though, so let's leave it for now.

**Comment by karfai** [comment]
The [compute platform](https://github.com/Xalgorithms/interlibr) as it is currently implemented [has changed](https://development.xalgorithms.org/architecture/core.architecture/). This is no longer relevant.

**Pull request closed without merging**
